communitiesuk/funding-service-design-assessment-store

LICENSE
Adds a license to the default template see https://www.gov.uk/service-manual/technology/making-source-code-open-and-reusable for context
=> BAU: Add MIT license

.github/workflows/deploy.yml
Essential we do this for this repo so we don't run in branch migrations
=> FS-1019: Restrict test deploys to main branch

manifest.yml
theory is that having 2 applications keys was causing the manifest to be interpreted in a weird way and databases being bound incorrectly
=> FS-2045: fix manifest.yml

scripts/import_from_application.py
Script was failing previously as the application store host was not specified i.e.
```
requests.exceptions.MissingSchema: Invalid URL '/applications?status_only=SUBMITTED&round_id=c603d114-5364-4474-a0c4-c41cbf4d3bbd': No scheme supplied. Perhaps you meant http:///applications?status_only=SUBMITTED&round_id=c603d114-5364-4474-a0c4-c41cbf4d3bbd?
```
=> FS-2040: add application store host

scripts/import_from_application.py
The import script was failing as it was missing the `forms` query parameter e.g.
```
2023-01-05T13:57:13.65+0000 [APP/TASK/import/0] ERR File "/home/vcap/app/scripts/import_from_application.py", line 29, in <module>
2023-01-05T13:57:13.65+0000 [APP/TASK/import/0] ERR form_jsons_list = application["forms"]
2023-01-05T13:57:13.65+0000 [APP/TASK/import/0] ERR KeyError: 'forms'
```
=> FS-2040: add forms parameter to query string

api/routes/subcriterias/get_sub_criteria.py, tests/test_get_sub_criteria.py
- Refactor log to use debug instead of error 
- Also add test for good day/bad day
=> BAU: Refactor log to use debug instead of error

db/queries/scores/queries.py, tests/test_db_function.py
- Fix latest sub criteria score query limit
- Add test to verify changes function as intended
Previously, we were limiting to `1` - which was only returning a single score for the entire application id.
What we actually want, is the latest score for every unique sub criteria id in an assessment record.
=> FS-2146: Fix latest sub criteria score query

api/routes/subcriterias/get_sub_criteria.py, tests/test_get_sub_criteria.py
We're splitting on `: ` from the left, without any limit.  The user has entered a `:`  as part of their description, so we're splitting pre-maturely and incorrectly, which subsequently messes up the float coercion on the frontend. Changing to `rsplit` with a limit of `1`, should fix the immediate issue.
Relevant links (for reference):
- https://github.com/communitiesuk/funding-service-design-assessment-store/pull/58#discussion_r1047347313
- [slack thread](https://communities-govuk.slack.com/archives/C02PHBER287/p1673882389522519)
- [JIRA FS-2188](https://digital.dclg.gov.uk/jira/browse/FS-2188)
=> FS-2188: Change to use rsplit with limit of 1

db/queries/comments/queries.py, tests/test_db_function.py
Previously we returned all comments only if a parameter of `theme_id=score` was supplied.
This is not semantically meaningful and was presumably done to match the similarly confusing behaviour in the frontend.
This changes the behaviour to return all comments for a subcriteria if no theme is supplied. It maintains the old behaviour for backwards compatibility until the frontend is deployed without using `theme_id=score`
=> FS-2294: return all comments if theme_id not supplied

api/routes/assessment_routes.py, db/queries/__init__.py, db/queries/flags/queries.py, tests/test_db_function.py, tests/test_routes.py
The reason for the inaccurate metric is because the endpoint retrieving the applications data retrieves the following metrics for example: 
{'assessing': 0, 'completed': 3, 'flagged': 0, 'not_started': 7, 'qa_completed': 3, 'stopped': 0, 'total': 10}
At this point the metric will show 3 QA Completed, however, if we now FLAG an application, although it is still QA completed, since the latest flag is "Flagged", the following will show:
{'assessing': 0, 'completed': 3, 'flagged': 1, 'not_started': 7, 'qa_completed': 2, 'stopped': 0, 'total': 10}
The reason for this is because the endpoint retrieving 'qa_completed' will only count it as true if that is the latest flag. 
The query used to retrieve the amount of qa_completed applications previously only returned true IF qa_completed was the …
=> FS-2289 - Fixed metric issue, now uses retrieve flags endpoint

.github/workflows/tag-to-release.yaml
Change description
Since moving to an Enterprise org it appears GITHUB_TOKEN has defaulted to restricted permissions as described in https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token so we need to specify the correct permissions for our workflows.
[ - ] Unit tests and other appropriate tests added or updated
[ - ] README and other documentation has been updated / added (if needed)
[ - ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
If manual testing is needed, give suggested testing steps
Screenshots of UI changes (if applicable)
=> update tagging action permissions

requirements-dev.txt, requirements.in, requirements.txt, tests/conftest.py
Fixing app crashes on test because the new utils package was requiring pytest at runtime. This PR brings in a new version of utils that fixes that, and updates the package name accordingly.
- [ n/a] Unit tests and other appropriate tests added or updated
- [ n/a] README and other documentation has been updated / added (if needed)
1. Install dependenices
2. Remove pytest using `pip uninstall pytest`
3. Run app using `flask run`, app should start without import errors
n/a
=> changing utils imports

scripts/location_utils.py, scripts/populate_location_data.py
Part of: https://digital.dclg.gov.uk/jira/browse/FS-2468
A fix to the 'populate_location_data.py' script. The new round has a number of applications over the api limit for postode.io. This fix chunks queries to the postcode api to remain below the limit.
I also took the opportunity to add some useful logging.
=> Fix - chunk postcode.io data and add detail to location script logging

scripts/location_utils.py
This PR adds a condition that will result in a "Not found" response if the Project information page for a community asset address cannot be found. This behavior will only occur in local environments since the Project information address field is required.
=> FS-2640-location-is-missing-for-some-applications

.pre-commit-config.yaml, config/envs/development.py, db/queries/assessment_records/queries.py, db/queries/flags/queries.py, tasks/db_tasks.py
- Use a single query to get applications with a qa complete flag
- Fix f string and duplication errors in seeding script
- Set FSD log level in development configuration
- Also set line length to 120 as per the [GDS way](https://gds-way.cloudapps.digital/manuals/programming-languages/python/python.html#maximum-line-length-of-120-characters)
---
=> FS-2683: Change query for qa complete

manifest.yml
Change description
Adding the health checks invocation timeout to assessment store for Test env in case it may need it. 
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#health-check-invocation-timeout
https://cli.cloudfoundry.org/en-US/v6/v3-set-health-check.html
How to test
Once this PR is merged run the e2e tests for Assessment locally and the tests should pass without any environment issues.
Screenshots of UI changes (if applicable)
N/A
=> BAU:  Add health-check-invocation-timeout 

requirements-dev.in, requirements-dev.txt, requirements.in, requirements.txt
Upping the psycopg2-binary to 2.9.6 and upgrading pip-tools so it works locally
Clone code to a mac, create a venv, install requirements and run
n/a
=> bumping versions for compaitibility on M1 macs

api/routes/subcriterias/get_sub_criteria.py, tests/test_get_sub_criteria.py
https://digital.dclg.gov.uk/jira/browse/FS-3045
Adding formatting for the month year fields so they not longer display as a object with key value pair when viewing themes with a add another section
If you navigate to the Proposal summary and milestones sub criteria and select the Milestones theme, you will see the the month year field now longer displays and a object with key value pairs
=> FS-3045 Adding fix for formatting month year in add another

config/mappings/cof_mapping_parts/cof_r3_scored_criteria.py
adding '(optional)' text to engangement -> local support -> upload evidence
=> bau-add-optional-text-to-cofr3-config

config/mappings/nstf_mapping_parts/nstf_r2_unscored_sections.py
- Add missing `zuCRBk` from NSTF config
- Will now show in the answers
- Also add dates so we can differentiate between values
---
=> FS-3098: Add missing field from NSTF config

config/mappings/nstf_mapping_parts/nstf_r2_unscored_sections.py
https://dluhcdigital.atlassian.net/browse/FS-3154
Changing the presentation type of two fields to be currency
Go to the Funding required page Funding required, building works and match sub criteria
Questions like How much revenue are you applying for? 1 April 2023 to 31 March 2024 should not show a currency value
=> adding currency presentation type

config/mappings/cof_mapping_parts/cof_r3_unscored_sections.py
https://dluhcdigital.atlassian.net/browse/FS-3180
"Does your organisation use any other names?" is now in the correct position. 
Check the organisation information page
=> FS-3180 - Moving the other names questions to correct position

config/mappings/cof_mapping_parts/cof_r3_unscored_sections.py
- Noticed this when working on support with Pete/Kavya
- Change identifier so the "Other" answer shows on assessment
=> BAU: Fix wrong identifier

api/routes/assessment_routes.py, tests/test_db_tag_associations.py
- Return an empty list if no tags, so we get a list and a `200` response
- If we return `None`, it implicitly gives us a `204`
https://communities-govuk.slack.com/archives/C02PHBER287/p1689942993480279
=> BAU: Return empty list if no associated tags

.vscode/launch.json, api/routes/assessment_routes.py, config/mappings/assessment_mapping_fund_round.py, db/queries/assessment_records/queries.py, openapi/api.yml, tests/test_db_function.py, tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/FS-3273
Added a output tracker so user can run the report themselves. 
Iv tried to make this partially dynamic so eventually we could potentially pass in the field we want from a UI and run a report that way
to be used with https://github.com/communitiesuk/funding-service-design-assessment/pull/369
Click the new Assessment tracker export link on the landing page as highlighted from the picture
=> Fs 3273 output tracker

api/routes/progress_routes.py, openapi/api.yml, tests/test_db_scores.py
Bug fix: Team dashboard - Progress counter is displaying based on the amount of scored sub criteria for a round.
https://dluhcdigital.atlassian.net/browse/FS-3291
**BEFORE**
**AFTER**
=> add fund and round to get progress stats

db/queries/assessment_records/_helpers.py, db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/browse/FS-3440
Currently location extraction errors are not logged in sentry during application import
- Log sentry error when location keys are not valid or invalid postcode provided
- Submit an application with invalid postcode in the projection information section
- Wait for the automatic import to trigger (send & receive message (~ 60sec))
- Observe that import should be successful & location errors are logged to sentry (or in assessment container logs if testing locally)
=> FS-3440 log location extraction errors to sentry

.env.development, .github/workflows/manual-dev-deploy.yaml, .pre-commit-config.yaml, README.md, config/envs/dev.py, config/envs/development.py, config/envs/unit_testing.py, copilot/environments/addons/funding-service-magic-links.yml, copilot/fsd-assessment-store/addons/fsd-assessment-store-cluster.yml, pytest.ini
https://dluhcdigital.atlassian.net/browse/FS-3441
- Added pre-commit 'Yelp/detect-secrets' to prevent committing of secrets to code base
- Ignore false positives by marking them with `pragma: allowlist secret`
- disabled the plugin `HexHighEntropyString` which tend to detect lot of false positives
- Add a secret/API/password to any of the file type
For eg. `API_KEY= "125fdfbdjhbj5989"`
- stage the file & commit it.
- Notice the commit is failed with errors.
=> FS-3441 added yelp hook for secrets

db/models/flags/assessment_flag.py
https://dluhcdigital.atlassian.net/browse/FS-3468
In SQLAlchemy, when you retrieve an object using a query (such as db.session.scalar(statement) in your code), the default behavior is to load all attributes and relationships of that object eagerly unless you specify otherwise. So, in the code snippet, even though were using defer to defer loading of the jsonb_blob column, all other attributes and relationships of the AssessmentRecord object will still be loaded eagerly by default.
If the flag_update relationship is not a direct relationship to AssessmentRecord but is a relationship on another related object, such as Flag, it will not be loaded eagerly by default when you retrieve an AssessmentRecord object.
Eager loading vs Lazy loading
When to Use Each Approach:
Lazy Loading: Use lazy …
=> add eager loading for flag updates on asessment flag table relationship

copilot/fsd-assessment-store/addons/fsd-assessment-store-cluster.yml
https://dluhcdigital.atlassian.net/browse/FS-3457
Change description
Add in Bastion's security group into the fsd-assessment-store DB's inbound rules.
Tested by using the aws ssm connection through bastion and being able to connect into the postgres DB.
[n/a] Unit tests and other appropriate tests added or updated
[n/a] README and other documentation has been updated / added (if needed)
Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
If manual testing is needed, give suggested testing steps
Screenshots of UI changes (if applicable)
=> FS-3457 - Add ingress to DB to allow Bastion connectivity

db/migrations/versions/~2023_10_04_1057-342b7a05b923_.py, db/models/assessment_record/assessment_records.py, db/queries/assessment_records/queries.py
- Adds a column `is_withdrawn` to assessment records, which acts as a flag to determine whether a record is marked as withdrawn
- The queries have been updated to not pull back any withdrawn applications, so we essentially "hide" it from the user interface
- This is done to match a support query to "withdraw" an application without losing the data, it would be good to have an option in the UI for this though to allow lead assessors to do this
---
=> FS-3575: Add is_withdrawn flag and update queries

api/routes/subcriterias/get_sub_criteria.py
https://dluhcdigital.atlassian.net/browse/FS-3670
Display `Not Provided` when none or empty string is provided
=> FS-3670 display `Not Provided` when none or empty string

api/routes/subcriterias/get_sub_criteria.py, config/mappings/cyp_mapping_parts/r1_unscored_criteria.py
https://dluhcdigital.atlassian.net/browse/FS-3676
https://dluhcdigital.atlassian.net/browse/FS-3677
Appended `optional` to requested fields
=> FS-3676 minor fixes for cyp

api/routes/subcriterias/get_sub_criteria.py
https://funding-service-design-team-dl.sentry.io/issues/4573667007/events/2c0d55f397a645b8bc1f612[…]=4504418765963264&referrer=alert-rule-issue-list
[FS-3698](https://dluhcdigital.atlassian.net/browse/FS-3698)
When partner organisations details are not provided, answers has `None` value. Refactored the code to include `None` checks
[FS-3698]: https://dluhcdigital.atlassian.net/browse/FS-3698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FS-3698 fix bug when None type found in formatted_answers

config/mappings/assessment_mapping_fund_round.py
https://dluhcdigital.atlassian.net/browse/FS-3745
Adding config for the Export applicant information functionality 
Click the Export applicant information on DPIF
=> FS-3745 Adding assessor export config

config/mappings/dpif_mappping_parts/r2_unscored_criteria.py
Fix the unscored criteria config for dpif to allow assessment to display the "About your organisation and future work" flag
Check the assessment frontend has the "About your organisation and future work" flag for dpif assessments
=> FS-3815: Update dpif unscored criteria

copilot/fsd-assessment-store/addons/fsd-assessment-store-cluster.yml
FS-3880 - Change DB storage-at-rest to be encrypted as a result of PEN testing
NOTE: Deletes the database so data re-migration is required.
=> FS-3880 - Encrypt DBs

config/mappings/cof_mapping_parts/r3w3_unscored_sections.py
https://dluhcdigital.atlassian.net/browse/FS-3995
Adding in question Grants from this fund cannot be used to buy the freehold or premium on the lease of a publicly owned asset. Money must only be used for renovation and refurbishment costs to unscored sections in Asset information under asset ownership
Complete an application, then navigate to assessment. Click the Asset information sub criteria, The added question should be under Asset ownership
=> FS-3955 Adding Question to Unscored sections

db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/browse/FS-3279
https://dluhcdigital.atlassian.net/browse/FS-3721
- Filter null values in the address field
- Extract plain text from `freeText` type and display in the exported application .
=> FS-3279 filter null values in address field

api/routes/__init__.py, api/routes/assessment_routes.py, openapi/api.yml, tests/test_routes.py
- Change how the `get-stats` endpoint works, now takes `round_ids` as a post body
- Now returns a dictionary of `round_id` to `assessment_stats` basically
---
=> BAU: Make `get-stats` a bulk endpoint

openapi/api.yml
This change reintroduces the previously deprecated API endpoint to ensure backward compatibility and uninterrupted service during the transition period of deploying frontend and backend updates separately. By maintaining both the old and new endpoints, we prevent potential downtime or accessibility issues for users.
=> BAU: Re-add old API endpoint for seamless deployment

config/mappings/cof_mapping_parts/eoi_unscored_sections.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4249
https://dluhcdigital.atlassian.net/browse/FS-4267
- remove extra s from "About your asset" sub criteria
- Correct the question to "How your organisation is classified" from "How is you organisation classified"
=> FS-4249-extra-s-in-about-your-assset-sub-criteria

config/mappings/assessment_mapping_fund_round.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4259
Added translation: Missing column header in " Export applicant information" for Welsh EOI applications. "Do you already own the asset?"
Before
After
=>  FS-4259-missing-welsh-column-translation-added-for-csv-file

requirements-dev.txt, requirements.txt
This reverts commit e62def61fc70f91c23601361efd97e148e2352e9.
- Issues with connexion 3.0.6 (so far failed unit tests are noticed)
- Reverting back the changes
- created a ticket https://dluhcdigital.atlassian.net/browse/FS-4302 to keep track of this issue
=> Revert "Bump connexion from 2.14.2 to 3.0.6 (#424)"

db/queries/assessment_records/queries.py
- If "answer" doesnt exist in the field, we are throwing an Exception
- Instead, provide a blank string on the export instead, so we still get the export
=> BAU: Prevent KeyError when answer is missing

config/mappings/assessment_mapping_fund_round.py, db/queries/assessment_records/queries.py, tasks/db_tasks.py, tests/test_data/hand-crafted-apps.json, tests/test_db_function.py
For COF R4W1 they want additional fields in the applicant info export (see ticket for the list). This PR:
- Adds those fields
- Adds unit tests for those fields
- Updates the `get_export_data` function to allow for new field types (postcode, sum of values)
- Updates the seed data script to work properly
---
- Navigate to assessment
- Click 'Export Applicant Information' for COF R4W1
- View the CSV and check all fields hold correct values
=> Fs 4315 cof export

.vscode/launch.json, db/migrations/versions/~2024_04_16_1018-dac03038236f_.py, db/models/score/enums.py, db/models/score/scores.py
Discovered that the migrations files aren't up to date with the model files. This PR creates a new migration that matches the model files. Changes are:
- setting assessment_record.is_withdrawn to `is_nullable=True`
- changing the name of the scoring system enum from `scoring_system_enum` to `scoring_system`
- Run DB upgrade to revision `dac03038236f`
- Run DB downgrade to revision `6c8205510de6`
=> BAU Renaming scoring enum and setting is_withdrawn nullable=false

api/routes/_helpers.py, api/routes/assessment_routes.py, db/queries/assessment_records/queries.py
This PR implements two changes to the applications_overview endpoint:
- Avoids N+1 queries by preloading related data for AssessmentRecord
- Compresses the response from the applications_overview endpoint by using minified json.
Observe load time in test environment
=> FS-4004: Preload AssessmentRecord properties and compress response

db/queries/scores/queries.py, services/data_services.py
Use a WARNING rather than an ERROR when a fund-round uses the default scoring system.
Additionally..
Warn is deprecated so fix an instance of this:
=> change logging level

config/mappings/assessment_mapping_fund_round.py, db/queries/assessment_records/queries.py, tests/test_db_function.py
[FS-446](https://dluhcdigital.atlassian.net/browse/FS-4446)
Rearranged the default order of the columns so that Score comes directly after Date submitted regardless whether there is a score entered or not. Previously Score and Score Subcriteria could be swapped depending on if the first row had been scored yet)
Open OUTPUT_TRACKER report for a window that has applications but no scores. Open OUTPUT_TRACKER for a window that has applications and are all scored. The columns should be in the same order for both reports.
Before fix (COF OUTPUT_TRACKER report):
NSTF OUTPUT_TRACKER report:
[FS-446]: https://dluhcdigital.atlassian.net/browse/FS-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FS-4446: Consistent CSV File Columns

db/queries/assessment_records/queries.py, tests/test_db_allocation_associations.py
Each allocation association (work assignment) contains a log to record history. This PR adds the assigner id for each action in the log. 
=> Store assigner in allocation association log

.pre-commit-config.yaml, requirements-dev.in, requirements-dev.txt
Bumps our local pre-commit version to be >=4.0. This matches what runs in pre-commit.ci, so is best to keep roughly in sync.
In particular this bump has been prompted by CI failures on the assessment-store, where one of the installed hooks is incompatible with v4 of pre-commit because the `python_venv` "language" has been removed. We don't see this issue locally on that repo because we're still running an older version of pre-commmit.
See also https://github.com/PyCQA/docformatter/issues/289
=> Upgrade pre-commit

_helpers/task_executer_service.py
Fixing an error in logging a warning, and correcting a variable name
=> Fixing log message and typo in var name

copilot/fsd-assessment-store/manifest.yml
This will help us migrate from the "microservice"-y application-store to a more consolidated pre-award-stores service.
Ticket: https://mhclgdigital.atlassian.net/browse/FSPT-122
=> BAU: Move application store api host to AWS parameter store secret

copilot/fsd-assessment-store/manifest.yml
This is because the `recreate` deployment method leads to downtime, which can cause tests to flake. It is not any faster than a normal deployment, and causes tests to break. I am not sure why it was chosen to begin with.
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment-rolling
=> Turn off recreate deploys in test environment

.vscode/settings.json
Remove the colour customisations specified at the repository configuration level.
Developers can still specify their own customisations for the workspaces.
The current version of vscode has very little contrast with the chosen colour scheme which makes it hard to use.
This also removes an override for formatting on saving which can also now be chosen by the developer based on their setup -- formatting issues should be caught in pre-commit checks both locally and during the CI process.
Example of low contrast icons with the repository specified colour scheme
- ~[ ] Unit tests and other appropriate tests added or updated~
- ~[ ] README and other documentation has been updated / added (if needed)~
=> BAU Dont override user workspace colour preferences

copilot/fsd-assessment-store/addons/notificatio-queue.yml
https://mhclgdigital.atlassian.net/browse/FSPT-110
I missed giving assessment-store write access to the notification queue previously. Somehow this wasn't picked up by tests :(
=> Allow assessment-store to write to notification queue
