communitiesuk/funding-service-design-assessment-store

- manifest.yml
Add initial manifest for PaaS deployment
> FS-1020: add initial manifest

- db/models/sub_criteria.py
adding the data model for subcriterias
> FS-1112 Implement data model in Assessment for criteria and Subcriteria

- Dockerfile
Add dockerfile including database dependencies and running migrations.
> FSD-657: add dockerfile

- requirements-dev.txt
- requirements.in
- requirements.txt
Add missing `psycopg2` dependency which was causing app to fail when run with postgres database.
> BAU: add missing postgres dependency

- .github/workflows/deploy-docs.yaml
- .pre-commit-config.yaml
- api/__init__.py
- db/__init__.py
- tests/__init__.py
docformatter broke the docs.
This fixes them.
Also, could someone please allow github pages to publish from main?
> bau-fix-docs

- db/queries/assessment_records/queries.py
- tests/test_routes.py
Asset type changed from like to exact match as it has a set of bounded values
> Asset type changed from like to equal

- .github/workflows/deploy.yml
Passing params to shared workflow to run the tests on dpeloy
> adding params to run tests on deploy

- db/schemas/schemas.py
- tests/_expected_responses.py
- tests/test_db_function.py
Follow up from this frontend change: https://github.com/communitiesuk/funding-service-design-assessment/pull/71
> Change project_reference to short_id

- api/routes/_helpers.py
- api/routes/assessment_routes.py
- db/models/assessment_record/assessment_records.py
- db/models/comment/comments.py
- db/queries/comments/queries.py
- db/queries/scores/queries.py
- tests/_expected_responses.py
- tests/test_assessment_mapping_fund_round.py
- Given a sub criteria has been scored, mark it as completed
- If it has a comment, but is not scored, mark it as in progress
- If neither of these, then the sub criteria is not started
- Pull scores back from database and calculate total score
Other relevant JIRAs: [FS-2106](https://digital.dclg.gov.uk/jira/browse/FS-2106) [FS-2105](https://digital.dclg.gov.uk/jira/browse/FS-2105) [FS-1942](https://digital.dclg.gov.uk/jira/browse/FS-1942)
> FS-2000: Dynamically pull score & status from database (back-end)

- api/routes/assessment_routes.py
- db/models/assessment_record/db_utils.py
- tests/test_data/hand-crafted-apps.json
- tests/test_db_function.py
- Start listening to inserts on `Score/Comment`
- After each insert, update `workflow_status` of relevant `AssessmentRecord` if not done already
> FS-2105: Add event to update workflow status on inserts

- app.py
- manifest.yml
Add Sentry integration as per other apps
> BAU: add sentry integration

- api/routes/__init__.py
- api/routes/assessment_routes.py
- api/routes/flag_routes.py
- db/migrations/versions/78d40ab26730_.py
- db/models/__init__.py
- db/models/assessment_record/assessment_records.py
- db/models/flags/__init__.py
- db/models/flags/enums.py
- db/models/flags/flags.py
- db/queries/__init__.py
- db/queries/flags/queries.py
- db/schemas/schemas.py
- openapi/api.yml
- openapi/components.yml
- tests/test_db_function.py
[Add endpoint to retrieve banner state](https://github.com/communitiesuk/funding-service-design-assessment-store/pull/75/commits/8279607efe5281a364be1466a47740d429ba48d4)
- Update metadata to use Enum as was seeing error
[Add flag routes and database model/migration](https://github.com/communitiesuk/funding-service-design-assessment-store/pull/75/commits/2f1a616e6145b90c15dc4ad863ebfa58d967f992)
- Get request to return all flags for a given application
- Post request to create a flag for a given application
- Migration script introduced to create the flags table in db
> FS-2014: Add endpoint to retrieve banner state

- db/queries/assessment_records/queries.py
- scripts/import_from_application.py
Assorted fixes to the import script
> FS-2040: fixes for import script

- config/mappings/mapping_parts/unscored_sections.py
Fixing questions being duplicated in subsidy control and adding correct captions to some confirmation boxes
> BAU fixing question config

- config/mappings/mapping_parts/scored_criteria.py
- tests/test_assessment_mapping_fund_round.py
- tests/test_db_function.py
- tests/test_routes.py
FS-2137: theme appearing wrong sub criteria.  Adding new subcriteria under existing criteria to house theme under community benefits as per mappings
> FS-2137: Fix question/theme/subcritera mappings

- api/routes/__init__.py
- api/routes/assessment_routes.py
- api/routes/progress_routes.py
- db/queries/__init__.py
- db/queries/progress/queries.py
- db/schemas/schemas.py
- openapi/api.yml
- tests/test_db_function.py
Just some functionality improvement
> FS-1355-assessment-progress-percentage

- api/routes/flag_routes.py
- db/queries/__init__.py
- db/queries/assessment_records/queries.py
- db/queries/flags/queries.py
- tests/test_db_function.py
- Show Flagged on assessor team dashboard
- Fix filters for Flagged applications, and unhandled statuses
See: https://github.com/communitiesuk/funding-service-design-assessment/pull/125
Video demo:
https://user-images.githubusercontent.com/117724519/211817671-47e51f30-bee5-4037-b822-81c1ffed6104.mp4
> FS-2149: Show Flagged & fix filters

- api/routes/__init__.py
- api/routes/progress_routes.py
- openapi/api.yml
- tests/test_db_function.py
- Start posting data as a json body as opposed to query params
https://sentry.io/organizations/funding-service-design-team-dl/issues/3850987122/?referrer=slack
> BAU: Change progress endpoint to post

- scripts/location_utils.py
Script is failing on test, adding debug info
> adding in response validation and printing error

- db/schemas/schemas.py
- tests/test_routes.py
Nested flags into application_overview schema to retrieve flags with the application, for use on dashboard to display STOPPED in status if STOPPED is the most recent
> Nest flags in overview

- db/queries/assessment_records/queries.py
- tests/_expected_responses.py
https://digital.dclg.gov.uk/jira/browse/FS-2017
Show "Flagged" status in the assessment dashboard
> remove flag as status

- README.md
- db/queries/assessment_records/queries.py
- openapi/api.yml
- tasks/db_tasks.py
- tests/_db_seed_data.py
- tests/_expected_responses.py
- tests/conftest.py
- tests/test_data/flags.py
- tests/test_data/hand-crafted-apps.json
- tests/test_db_function.py
- tests/test_routes.py
Fix filter search on status or flag
https://digital.dclg.gov.uk/jira/browse/FS-2259
https://digital.dclg.gov.uk/jira/browse/FS-2249
https://digital.dclg.gov.uk/jira/browse/FS-2250
https://digital.dclg.gov.uk/jira/browse/FS-2246
> Fix filter search on status or flag

- api/routes/__init__.py
- api/routes/assessment_routes.py
- openapi/api.yml
- tests/test_routes.py
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
https://digital.dclg.gov.uk/jira/browse/FS-2184
Adds a GET method to the API to allow retrieval of the application JSON blob. This is then used to produce a text file containing all questions and answers 
- [ X] Unit tests and other appropriate tests added or updated
- [ n/a] README and other documentation has been updated / added (if needed)
- [ .] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
Use the swagger interface (screenshot below) and request the json for a known application id
> FS 2184 - Enable application export for contracts

- api/routes/assessment_routes.py
Small bug fix used in https://github.com/communitiesuk/funding-service-design-assessment/pull/223
> FS-2567: Fix bug with workflow status

- scripts/README.md
- scripts/location_utils.py
- scripts/populate_location_data.py
This PR  returns a dictionary with default values indicating that a location was not found.
> FS-2640-location-missing-for-some-applications

- config/mappings/assessment_mapping_schema.py
Note: Evolved from https://github.com/communitiesuk/funding-service-design-assessment-store/pull/155 & https://github.com/communitiesuk/funding-service-design-assessment/pull/215
Relates to: https://github.com/communitiesuk/funding-service-design-assessment/pull/235
- Add new schema changes for client-side upload component
- This is a relatively small change, but will come into place after a round with the new upload component
> BAU: Rendering files from client-side upload

- .gitignore
- .vscode/launch.json
- .vscode/settings.json
- Dockerfile
- api/routes/assessment_routes.py
- openapi/api.yml
- requirements-dev.in
- requirements-dev.txt
Jira Ticket
https://digital.dclg.gov.uk/jira/browse/FS-2618
Implement count based on filter returns. Updated Dockerfile to comply with debugger(https://github.com/communitiesuk/funding-service-design-docker-runner/pull/33)
- Open the Assessment dashboard & select a fund/round
- Apply any filters & observe the count
> Fs 2618 count for filters

- .vscode/launch.json
- README.md
- config/mappings/assessment_mapping_fund_round.py
- db/queries/assessment_records/_helpers.py
- scripts/import_from_application.py
- tasks/db_tasks.py
- tests/_application_store_json.py
- tests/_db_seed_data.py
- tests/_helpers.py
https://digital.dclg.gov.uk/jira/browse/FS-3001
Refactored the code to seed  COF R3 & NSTF assessments
`docker exec -it <container_id> invoke seed_dev_db`
To avoid the interactive prompt
`docker exec -it <container_id> invoke seed_dev_db --fundround COFR3W1 --appcount 1`
`docker exec -it <container_id> invoke seed_dev_db --fundround NSTFR2 --appcount 1`
If you are using VS-Code, select the  `Seed Applications in assessment-store` config  & launch
> Seed-assessments-for-other-funds

- api/routes/__init__.py
- api/routes/flag_routes.py
- db/queries/flags/queries.py
- openapi/api.yml
https://digital.dclg.gov.uk/jira/browse/FS-2779
Created an endpoint to retrive flag data by id
> added an endpoint to get flag by id

- db/queries/assessment_records/queries.py
https://digital.dclg.gov.uk/jira/browse/FS-3011
https://digital.dclg.gov.uk/jira/browse/FS-3013
Sort the flag data by date created in assessment records API
> Fs 3013 correct status in dashboard page

- .vscode/launch.json
- README.md
- config/mappings/assessment_mapping_fund_round.py
- db/queries/assessment_records/_helpers.py
- db/queries/assessment_records/queries.py
- scripts/README.md
- scripts/import_from_application.py
- scripts/location_utils.py
- scripts/populate_location_data.py
- tests/_expected_responses.py
- tests/test_cof_import_mapper.py
- tests/test_import_applications.py
- tests/test_location_utils.py
https://digital.dclg.gov.uk/jira/browse/FS-3022
https://digital.dclg.gov.uk/jira/browse/FS-3023
- Refactored `get_postcode_from_questions` function to work with other funds
- Implemented location extraction in the `derive_application_values` function part of import script(so for future imports no need to run `populate_location_data` script)
- Make location data consistent to `Not Available` when not found
- Improved the import & populate script working with shortnames (see below How to test section)
- Made import script resilient by logging the failed application_id and continuing the import ([FS-3023](https://digital.dclg.gov.uk/jira/browse/FS-3023))
- Updated read me file
`docker exec -it <container_id> python -m …
> Fs 3022 generalise populate location data for other funds

- config/mappings/cof_mapping_parts/cof_r3_scored_criteria.py
- config/mappings/cof_mapping_parts/cof_r3_unscored_sections.py
solve some display issues and apply updates to the COF R3 W1 Config
> bau-fix-cofr3w1-config-bugs

- api/routes/assessment_routes.py
- db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/browse/FS-3057
- part of the work for FS-3057
- fixed get flag v2 endpoint
> fix get_flag_v2 endpoint

- config/mappings/cof_mapping_parts/cof_r3_scored_criteria.py
- config/mappings/cof_mapping_parts/cof_r3_unscored_sections.py
this PR includes the bug fixes for: FS-3079, FS-3091, FS-3092, FS-3094, FS-3095
> bau-cof-r3-config-bugs

- config/mappings/assessment_mapping_schema.py
- config/mappings/nstf_mapping_parts/nstf_r2_unscored_sections.py
- Add currency format type, always formatted as GBP number to 2 dp
---
> FS-3154, FS-3072: Show currencies

- config/mappings/cof_mapping_parts/cof_r3_scored_criteria.py
- config/mappings/cof_mapping_parts/cof_r3_unscored_sections.py
This PR includes bug fixes from: FS-3156, FS-3157, 3120
> Bau cofr3 config bugs wave 3

- config/mappings/nstf_mapping_parts/nstf_r2_unscored_sections.py
Fixing bug cause I changed the wrong thing
> BAU: Fix bug

- config/mappings/cof_mapping_parts/cof_r3_scored_criteria.py
https://dluhcdigital.atlassian.net/browse/FS-3186
Fix presentation type for funding fields
> chenge presentation_type to currency for funding fields

- db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/browse/FS-3208
Fixed the search filter by status
> FS-3208 fix status filter

- .github/workflows/tag-to-release.yaml
- Fix syntax error in the yaml file
> BAU: Fix syntax error

- api/routes/assessment_routes.py
- db/queries/qa_complete/queries.py
- db/schemas/schemas.py
- tests/test_qa_complete.py
https://dluhcdigital.atlassian.net/browse/FS-3215
- fix stats output & remove duplicated schema for qa_complete
> fix stats & remove duplicated schema for qa_complete

- config/mappings/cof_mapping_parts/cof_r3_unscored_sections.py
https://dluhcdigital.atlassian.net/browse/FS-3229
> fs-3229-applicant-information

- api/routes/assessment_routes.py
- openapi/api.yml
https://dluhcdigital.atlassian.net/browse/FS-3215
https://dluhcdigital.atlassian.net/browse/FS-3139
- Extension to previous PR work (https://github.com/communitiesuk/funding-service-design-assessment-store/pull/235)
- Include "countries" search in get_stats (explictly required for DA)
> FS-3215 Include countries search in get stats function

- openapi/api.yml
https://dluhcdigital.atlassian.net/browse/FS-3139
- Extend DA auth stuff to team flag stats function
> extend DA auth stuff to team flag stats function

- db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?view=detail&selectedIssue=FS-3119
This PR refactors the existing script to now only export the latest final score of the subcriteria and justification.
> FS-3119-export-script-to-export-only-final-subsection-score

- db/queries/assessment_records/queries.py
- Add missing filter by tag functionality
> BAU: Add missing filter by tag functionality

- .github/workflows/deploy.yml
- .github/workflows/tag-to-release.yaml
* Rearranging the image name to be funding-service-design, not funding-design-service
+ref: FS-3217
+semver: minor
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS-3217: Fixing wrong order on fsd

- api/routes/__init__.py
- api/routes/tag_routes.py
- db/queries/tags/queries.py
- openapi/api.yml
- tests/test_db_tags.py
- tests/test_routes.py
Adding get tag method for use by the edit_tag page in assessment frontend - need to retrieve an individual tag by it's id
Use the swagger to call the get_tag_by_id method
> fs-3234 adding get_tag method

- api/routes/tag_routes.py
don't log error when no tags found
> bau- don't log error when no tags found

- config/mappings/assessment_mapping_fund_round.py
- db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/browse/FS-3159
Splitting date time across columns 
Check the file
> BAU - Separate score date and time

- db/queries/assessment_records/queries.py
Adding very small title change for csv
> Pushing title change fix

- config/mappings/assessment_mapping_fund_round.py
- db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/browse/FS-3306
Adding region and short id to excel exports
Test the excel esports and see the results
> Adding missing columns

- db/queries/assessment_records/queries.py
> Changing log level to warn

- .github/workflows/deploy.yml
- .github/workflows/manual-dev-deploy.yaml
- .github/workflows/tag-to-release.yaml
https://dluhcdigital.atlassian.net/browse/FS-3414
Change outdated reference to fds to fsd.
> FS-3414 Amend fds to fsd

- api/routes/tag_routes.py
- db/queries/tags/queries.py
https://dluhcdigital.atlassian.net/browse/FS-3254
- updated get tags functions to return all active & inactive tags
> Fs 3254 tagging turn sentry error into a warning when an assessor or lead assessor try to create the same tag

- config/envs/default.py
- copilot/environments/addons/assessment-import-queue.yml
- copilot/environments/addons/form-uploads.yml
- copilot/environments/addons/funding-service-magic-links.yml
- copilot/fsd-assessment-store/manifest.yml
- services/aws.py
Updating the code to include S3 and SQS 
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS-3089 - SQS addition for copilot deploy

- config/mappings/cof_mapping_parts/cof_r3w2_scored_criteria.py
Simply changing text according to the ticket here: https://dluhcdigital.atlassian.net/browse/FS-3436
> FS-3436: Change text of question

- tests/_application_store_json.py
- Add missing question to test json, so we can test properly
> FS-3434: Add missing question to test json

- config/mappings/cof_mapping_parts/cof_r3w2_unscored_sections.py
- Change numberField to textField to render as raw number
https://dluhcdigital.atlassian.net/browse/FS-3433
> FS-3433: Change numberField to textField to render as raw number

- db/models/tag/tags.py
see https://github.com/communitiesuk/funding-service-design-assessment-store/pull/286
> add eager load on tag types

- copilot/environments/addons/funding-service-magic-links.yml
https://dluhcdigital.atlassian.net/browse/FS-3519
Ensure all repos have the same copilot addons as assessment so it doesn't matter where it is created from.
> FS-3519 - Bring all copilot/environments/addons directories into line

- db/migrations/versions/~2023_10_04_1057-342b7a05b923_.py
https://github.com/communitiesuk/funding-service-design-assessment-store/pull/292
Duplicate as for some reason unit tests won't run on that PR?...
> BAU: Fix migration script

- _helpers/import_application.py
- api/routes/assessment_routes.py
- config/mappings/assessment_mapping_fund_round.py
- db/models/assessment_record/assessment_records.py
- db/queries/assessment_records/queries.py
- db/schemas/schemas.py
- openapi/api.yml
- tests/_application_store_json.py
https://dluhcdigital.atlassian.net/browse/FS-3537
- Updated fund_round_data_key_mappings for CYP
- updated application JSON template for CYP
- Update the seeding script for CYP
- Test the updated import script & make sure all fields are mapped accordingly
- Disable automatic import of application when mapping config is missing for a round(or not configured yet for a new round )
> Fs 3537 update import script configuration for cyp r1

- _helpers/import_application.py
- db/queries/assessment_records/queries.py
Minor improvements
- Change error to warning when import config is missing for an application
- Change to use application short reference in error/warning message instead of `application_id`
> minor improvements

- config/mappings/cyp_mapping_parts/r1_unscored_criteria.py
https://dluhcdigital.atlassian.net/browse/FS-3642
https://dluhcdigital.atlassian.net/browse/FS-3643
> patch - cyp config text changes

- config/mappings/assessment_mapping_fund_round.py
- db/queries/assessment_records/_helpers.py
- scripts/data_updates/FS-3661-total-funding-requested-cyp.py
https://dluhcdigital.atlassian.net/browse/FS-3661
> use correct revenue field keys

- api/routes/subcriterias/get_sub_criteria.py
- config/mappings/cyp_mapping_parts/r1_scored_criteria.py
- tests/test_get_sub_criteria.py
https://dluhcdigital.atlassian.net/browse/FS-3670
https://dluhcdigital.atlassian.net/browse/FS-3640
https://dluhcdigital.atlassian.net/browse/FS-3647
Minor fixes in rendering table fields
> FS-3640 fix table fields in mapping

- api/routes/subcriterias/get_sub_criteria.py
- config/mappings/assessment_mapping_fund_round.py
- tests/test_get_sub_criteria.py
cyp config patches
https://dluhcdigital.atlassian.net/browse/FS-3648
https://dluhcdigital.atlassian.net/browse/FS-3646
> add support for both capitilised key and non capitilized field types

- api/routes/subcriterias/get_sub_criteria.py
fix capitalisation from previous PR
https://github.com/communitiesuk/funding-service-design-assessment-store/pull/305
> fix capitalisation

- config/mappings/assessment_mapping_fund_round.py
- Add export config for contact details, CYP
> FS-3672: Add config for contact details CYP

- config/mappings/cyp_mapping_parts/r1_unscored_criteria.py
https://dluhcdigital.atlassian.net/browse/FS-3696
https://dluhcdigital.atlassian.net/browse/FS-3695
Add optional text for Tell us about your organisation's main activities and Alternative names of your organisation
Go to the about you organisation page to see the changes
> FS-3695, FS-3696, Add optional text

- config/mappings/assessment_mapping_fund_round.py
- db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/browse/FS-3644
Add the export config for CYP, also added method to neaten up lists in the excel doc.
> FS-3644 Added export config

- .github/workflows/copilot_deploy.yml
- .github/workflows/deploy.yml
- .github/workflows/environment.yml
- copilot/fsd-assessment-store/addons/fsd-assessment-store-cluster.yml
https://dluhcdigital.atlassian.net/browse/FS-3718
Amend the workflows so deployment to AWS dev happens on every commit, and deployment to AWS test happens on merge to master.  Also split out so all environments go via a common module.
> FS-3718 - Amend workflow to deploy automatically

- api/routes/subcriterias/get_sub_criteria.py
- db/queries/comments/queries.py
- tests/test_db_function.py
Missed updates to the queries to work with sql alchemy v2.x
> Fs 3054 fixes

- config/mappings/cyp_mapping_parts/r1_scored_criteria.py
https://dluhcdigital.atlassian.net/browse/FS-3756
Correcting mistake on the weighting percentages
> FS-3756 Updating weightings

- db/migrations/versions/~2023_11_10_1122-af78512b644f_.py
Handle literals in comment text data migration.
> handle literals in comment text

- config/mappings/dpif_mappping_parts/r2_scored_criteria.py
https://dluhcdigital.atlassian.net/browse/FS-3748
https://dluhcdigital.atlassian.net/browse/FS-3747
> fixes on PR desc

- copilot/fsd-assessment-store/manifest.yml
* Adding uat and production values to copilot config
+ref: FS-3780
+semver: minor
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)
- [*] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS-3780 Updating manifest

- .github/workflows/copilot_deploy.yml
Adding a quick check to confirm what copilot sees as an environment is what the workflow sees as the environment
+ref: FS-3780
+semver: minor
> FS-3780 Confirm env in copilot

- .github/workflows/copilot_deploy.yml
- copilot/fsd-assessment-store/manifest.yml
Add database migration scripts to the workflow
Double task count
+ref: FS-3799
+semver: minor
> Increase task count and add in migration scripts

- .github/workflows/deploy.yml
- .github/workflows/manual-dev-deploy.yaml
Update expired tokens
Run e2e tests
> Updated expired token

- db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-3808
> bug-fix/FS-3808-assessment-tracker-export-is-empty

- api/routes/comment_routes.py
- db/queries/comments/queries.py
bug-fix/FS-3685-view-assessment-activity-history-for-an-application
> bug-fix/FS-3685-view-assessment-activity-history-for-an-application

- api/routes/assessment_routes.py
- db/queries/assessment_records/queries.py
- openapi/api.yml
https://dluhcdigital.atlassian.net/browse/FS-3744
> app dpi filter support

- copilot/fsd-assessment-store/addons/fsd-assessment-store-cluster.yml
Add bastion sg to the bastion map in copilot
> BAU - Add bastion sg to copilot for prod

- requirements-dev.txt
- requirements.txt
Upgraded the cryptography library
> BAU - Updated Cryptography to 41.0.7

- config/mappings/cof_mapping_parts/r3w3_scored_criteria.py
- Add missing fields to cof r3w3 assessment config 
- Grant cost coverage
- Match funding usage amount
> FS-3972: Add missing fields to cof r3w3 assessment config

- config/mappings/cof_mapping_parts/r3w3_scored_criteria.py
https://dluhcdigital.atlassian.net/browse/FS-3977
https://dluhcdigital.atlassian.net/browse/FS-3976
https://dluhcdigital.atlassian.net/browse/FS-3975
Fix  for file names not rendering in all document section
Fix for file name on risks not showing
Fix for asset background
> BAU - Fixing wrong form names that cause file names not to render

- config/mappings/cof_mapping_parts/r3w3_unscored_sections.py
https://dluhcdigital.atlassian.net/browse/FS-3975
Fixing incorrect field id for Is this a registered Asset of Community Value (ACV)?
> Fixing incorrect field id

- config/mappings/cof_mapping_parts/r3w3_unscored_sections.py
https://dluhcdigital.atlassian.net/browse/FS-4006
Adding in missing questions for Job title of contact and Organisation Name
Go to Asset information and click Asset ownership a check if the questions are there
> FS-4006 Adding missing questions

- db/queries/assessment_records/_helpers.py
- tests/_application_store_json.py
- tests/test_data/hand-crafted-apps.json
https://dluhcdigital.atlassian.net/browse/FS-3989
Adding missing language to import queue script for that the language is correct on submitted applications. This fix the welsh export now working
Click Export applicant information and Assessment Tracker Export on COF round 3 window 3
> FS-3989 - Adding missing language to bulk insert

- config/mappings/assessment_mapping_fund_round.py
- db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/browse/FS-3279
Filter null values in address filed for welsh export function
> FS-3279 patch fix

- api/routes/assessment_routes.py
- api/routes/subcriterias/get_sub_criteria.py
- config/mappings/assessment_mapping_schema.py
- config/mappings/cof_mapping_parts/r3w3_scored_criteria.py
- config/mappings/cof_mapping_parts/r3w3_unscored_sections.py
- db/queries/assessment_records/queries.py
- tests/test_db_function.py
- tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/FS-4032
Adding fix for welsh documents not appearing in the areas that they should be
Create a welsh application a check the areas where document uploads should be. All document upload section is a good example
> Fix for Welsh upload documents

- .github/workflows/copilot_deploy.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
> BAU standardise deploy mechanism across envs

- copilot/fsd-assessment-store/addons/fsd-assessment-store-cluster.yml
https://dluhcdigital.atlassian.net/browse/FS-3945
Increase retention from 1 day to 8
Applied to dev and checked retention period has been amended.
> FS-3945 Increase retention period to 8 days

- config/mappings/cof_mapping_parts/eoi_unscored_sections.py
Removes unrelated checkbox components following https://github.com/communitiesuk/digital-form-builder/pull/472
> FS-4107: Remove old COF EOI unscored sections

- db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/browse/FS-4092
Fix tagging query to retrieve the latest unique associated tags
> FS-4092 update tags query

- db/models/assessment_record/assessment_records.py
- db/schemas/schemas.py
Extracting the submitted date from the application json as a column_property field on AssessmentRecord
> fs-4158 displaying submitted date

- config/mappings/assessment_mapping_fund_round.py
- config/mappings/cof_mapping_parts/eoi_unscored_sections.py
- db/queries/assessment_records/queries.py
https://dluhcdigital.atlassian.net/browse/FS-4209
https://dluhcdigital.atlassian.net/browse/FS-4161
https://dluhcdigital.atlassian.net/browse/FS-4103
Some EOI fixes
> FS-4209-4161-4103-COF-EOI-fixes

- config/mappings/cof_mapping_parts/eoi_unscored_sections.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4204
ordered questions as per the prototype
> FS-4204-ordered-questions-as-per-the-prototype

- config/mappings/assessment_mapping_fund_round.py
https://dluhcdigital.atlassian.net/browse/FS-4244
Adding welsh config for applicant export
> Fs 4244 welsh field names

- config/mappings/cof_mapping_parts/r4w1_unscored_sections.py
https://dluhcdigital.atlassian.net/browse/FS-4269
- Revert changes form previous [PR](https://github.com/communitiesuk/funding-service-design-assessment-store/pull/439)
- Fixed bug - file upload not showing for `Upload asset valuation or lease agreement` question
> FS-4269 revert changes

- copilot/fsd-assessment-store/manifest.yml
_'FS-4411: Reduce the number of tasking running and change to fargate-spot _
_Will check after deployment_
> FS-4411: Over-provision instance and change to Fargate-spot

- config/mappings/hsra_mapping_parts/r1_scored_criteria.py
- tests/_application_store_json.py
https://dluhcdigital.atlassian.net/browse/FFE-266
- Auction-costs removed
- Text changed as per requirements
> FS-4413: HSRA application updates

- app.py
Implementation class was missing so added it back
> FS-3535: adding fix for the assessment processing

- db/models/assessment_record/assessment_records.py
- db/queries/assessment_records/queries.py
- db/schemas/schemas.py
Update applications overview endpoint to include user association data. 
> Include user association data in application overview endpoint

- api/routes/__init__.py
- api/routes/assessment_routes.py
- api/routes/score_routes.py
- db/migrations/versions/~2024_07_17_1058-eecdd097df78_.py
- db/models/__init__.py
- db/models/assessment_record/assessment_records.py
- db/models/score/__init__.py
- db/models/score/scores.py
- db/queries/__init__.py
- db/queries/scores/queries.py
- db/schemas/__init__.py
- db/schemas/schemas.py
- openapi/api.yml
- openapi/components.yml
- tests/conftest.py
- tests/test_db_scores.py
- tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/FS-3982
> Add overall score percentage to application overview

- api/routes/tag_routes.py
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
- Content-Type specified in response for get_tags_for_fund_round route
> BAU-e2e-test-failure-fix

- project.toml
FS:4587: Exclude some repositories from built container images
- [ x] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS:4587: Exclude some repositories from built container images

- Procfile
Assessment-store can sometimes receive multiple API requests for the same high-level request originating from assessment. It would be beneficial to have multiple workers to be able to process concurrent requests. 
> Increase number of process workers for assessment-store

- copilot/fsd-assessment-store/manifest.yml
This will help us migrate from the "microservice"-y fund-store to a more consolidated pre-award-stores service.
Ticket: https://mhclgdigital.atlassian.net/browse/FSPT-108
> Read fund-store host from parameter store

- config/mappings/assessment_mapping_fund_round.py
- config/mappings/ctdf_mapping_parts/r1_unscored_sections.py
> Add CTDF config
